import json

def readFileToList(filename):
    with open(filename) as file_in:
        lines = []
        for line in file_in:
            lines.append(line)
        return lines;

def unsusLines(input):
    lines = input;
    newlines = []
    for j in range(len(lines)): # loop entries
        line = lines[j]
        tocut = 0
        
        if(len(line) == 1):
            continue
        

        for i in range(len(line)): # loop chars
            c = line[i]# getcurr

            if(c == ' '): # if whitespace, cut from string
                tocut = tocut + 1
            else:
                newlines.append(line[tocut:]) ## add to new list
                break;
    return newlines;

def getApiInitChunk(inlines):
    END_SECTION_KEYWORD = "#define API_Define_Styles"
    START_SECTION_KEYWORD = "#define API_Init"
    newlist = []
    started = False;
    for line in inlines:
        print(line)
        if(started == False and START_SECTION_KEYWORD in line):
            started = True
            print("started")
            continue
        if(started == True and END_SECTION_KEYWORD in line):
            print("end")
            newlist = newlist[1:]
            break
        
        if(started):
            newlist.append(line);
    return newlist;

def handleApiInit(lines):
    print(lines)
    functionsList = []

    for line in lines:
        step = 0;
        _dllname = ""
        _funcname = ""
        _calltype = ""
        _retType = ""
        _numArgs = ""
        argsTypeList = []
        finishDict = {}
        outerDict = {}
        currArgBuf = "";

        for c in line:
            if(c == '('): # begin name read
                step = 1;
                continue
            elif(c == ',' and step == 1): # begin func read
                step = 2
                continue
            elif(c == ',' and step == 2): # begin calltype read
                step = 3
                continue
            elif(c == ',' and step == 3): # begin rettype read
                step = 4
                continue
            elif(c == ',' and step == 4): # begin argnum read
                step = 5
                continue
            elif(c == ',' and step == 5): # begin argstype read
                step = 6
                continue
            elif(c == ')' and step == 6): # done
                #print(json.dumps(argsTypeList))
                #done
                finishDict['name'] = _funcname.replace("'", "")
                finishDict['externalName'] = _funcname.replace("'","")
                # get calltype to new format 11 = stdcall, 12 = cdecl
                if("dll_stdcall" in _calltype):
                    finishDict['kind'] = 11
                else:
                    finishDict['kind'] = 12
                
                finishDict['help'] = "AutoGeneratedExtension"
                ##
                #       1 = string, 2 = double
                ##
                if("ty_real" in _retType):
                    finishDict['returnType'] = 2
                    print(_retType)
                    print("found Returntype real")
                else:
                    finishDict['returnType'] = 1
                    print(_retType)
                    print("found Returntype string")

                finishDict['argCount'] = int(_numArgs)
                # Add args list
                argsListNode = dict()
                argsListNode['arg'] = argsTypeList
                finishDict['args'] = argsListNode;

                # push to dict
                #outerDict['function'] = finishDict
                functionsList.append(finishDict)
                

            ## determine where to write
            if(step == 1):
                _dllname += c;

            elif(step == 2):
                _funcname += c;

            elif(step == 3):
                _calltype += c;

            elif(step == 4):
                _retType += c;

            elif(step == 5):
                _numArgs += c;

            elif(step == 6):# read args to current buffer
                # catch ","
                if(c != ","):
                    currArgBuf += c
                    # ty_string = 1, ty_real = 2
                    if("ty_real" in currArgBuf):
                        argsTypeList.append(2)
                        currArgBuf = "" #reset buf
                    elif("ty_string" in currArgBuf):
                        argsTypeList.append(1)
                        currArgBuf = "" #reset buf
    #ret
    return functionsList;


def printlisttofile(lines):
    f = open("test.txt", "w")
    for line in lines:
        if(len(line) != 1):
            f.write(line);
    f.close();



